
nginx:
  build: ./serveur_nginx/
  links:
    - node1:node1
    - node2:node2
  ports:
    - "80:80"

db:
  image: mongo
  ports:
    - "27017"

node1:
  build: ./serveur_node/
  ports:
    - "3000"
  links:
    - db
  volumes:
    - /img/upload

node2:
  build: ./serveur_node/
  ports:
    - "3000"
  links:
    - db
  volumes_from:
    - node1
