nginx:
  build: ./nginx
  links:
    - node1:node1
    - node2:node2
  ports:
    - "80:80"

node1:
  build: .
  ports:
    - "3000"
  links:
    - db

node2:
  build: .
  ports:
    - "3000"
  links:
    - db

db:
  image: mongo
  ports:
    - "27017"
  environment:
    - MONGOHQ_URL=""
