version: '2'
services:
  nginx:
    build: ./gateway/
    links:
      - node:node
    ports:
      - "80:80"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  node:
    build: ./serveur/
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - /img/upload
    environment:
      DB_CNX: "mongo:27017"

