
nginx:
  build: ./nginx
  links:
    - node1:node1
    - node2:node2
  ports:
    - "80:80"
    
db:
  image: mongo
  ports:
    - "27017"

node1:
  build: .
  ports:
    - "3000"
  links:
    - db
  volumes:
    - /img/upload

node2:
  build: .
  ports:
    - "3000"
  links:
    - db
  volumes_from:
    - node1
